### ISSUE TITLE
Make sure example definitions emit required attributes

### ISSUE THREAD

**Issue by svrnm** [cisco-open/test-telemetry-generator#32]
The current example definitions are missing some resource/trace/... attributes that are mandatory by the otel spec or required by AppD cSaaS:

Resource Attributes:
* `service.name` is mandatory
* `service.namespace` is required for AppD cSaaS to set the Business Application, although it can be set via the collector config
* `telemetry.sdk.language` is required for AppD cSaaS to set a proper icon on the tier/node

Trace/Span Attributes:
* `http.methdod` is required by the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md) for servers & clients
* `http.url` & `net.peer.name` are required for http clients
* `http.scheme`, `http.target`, `nest.host.name` are required for the HTTP Server
* `db.system` is required for Databases
* `messaging.system`, `messaging.destination` are required for MQs
* There are some additional requirements per DB, MQ System, etc.
* Some requirements for HTTP, DB & Message Queues are listed here: [Troubleshooting AppDynamics For OpenTelemetry](https://docs.appdynamics.com/appd/22.x/latest/en/application-monitoring/appdynamics-for-opentelemetry/troubleshooting-appdynamics-for-opentelemetry)

In a second stop it would be cool if test-telemetry-generator could be configured to take care of those attributes automatically and only by turning on a flag those attributes will not be set (e.g. to test how a backend system reacts on payload that does not follow the spec)

**Comment by preet-dev** [comment]
@svrnm Linked a PR to address this. Other than the required attributes, I have added some recommended ones as well. I haven't updated the ones in `example-definitions/qa` as they are targeted towards AppD Cloud and at the time of commit worked fine on our platform. We can remove the definitions from this directory if required.
