### ISSUE TITLE
Add support for OTel events

### ISSUE THREAD

**Issue by preet-dev** [cisco-open/test-telemetry-generator#41]
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/semantic_conventions/events.md

**Comment by preet-dev** [comment]
@svrnm As per the OTel convention, adding the `event.name` and `event.domain` attributes to a `LogRecord` makes it an event. I know AppD is not yet following this as we have our own conventions which were setup before OTel added events conventions. We have the following ways of handling this:

* Add a `type` field in log definition which allows values - logs & events. When events is set, we add these 2 attributes automatically. 
* Just add some examples for OTel events based log definitions as well as AppD events based log definitions in examples with some details in the corresponding wiki.
* Do nothing since the OTel events convention can be read and appropriate attributes added by our users.

TIA.

**Comment by svrnm** [comment]
> Just add some examples for OTel events based log definitions as well as AppD events based log definitions in examples with some details in the corresponding wiki.

I would prefer that one, because it gives the most clarity. if we (appd) decide to move to the official way of doing things we still can remove those examples
