### ISSUE TITLE
Version mismatch in the release assets

### ISSUE THREAD

**Issue by tompoch** [cisco-open/test-telemetry-generator#77]
## Description

Current `Release v23.2.0` assets contain fatjars for version 0.18.0. 

## Expected Behavior

The release number is matching the filenames

**Comment by preet-dev** [comment]
As indicated in the file names, the version 0.18.0 is not for this project but for OpenTelemetry protos. Until last year we were doing parallel releases for proto versions 0.9.0 as well which is in maintenance mode only now. In general, it helps to know what version of OpenTelemetry we're working with so we have continued with this practice.

@svrnm Seems like this is causing some confusion. Should we remove otel proto version from future asset file names and just mention it clearly in the README?

**Comment by svrnm** [comment]
> As indicated in the file names, the version 0.18.0 is not for this project but for OpenTelemetry protos. Until last year we were doing parallel releases for proto versions 0.9.0 as well which is in maintenance mode only now. In general, it helps to know what version of OpenTelemetry we're working with so we have continued with this practice.
> 
> @svrnm Seems like this is causing some confusion. Should we remove otel proto version from future asset file names and just mention it clearly in the README?

Yes, that makes sense! Since we only support one version as of now we should be able to do it that way, if this will change again in the future, we might need to find a better way to address that.

**Comment by preet-dev** [comment]
Sure, I will add this information in the README. We will also have it in release notes instead of release assets.
