### ISSUE TITLE
Allow handling of user defined JEL expression implementations

### ISSUE THREAD

**Issue by preet-dev** [cisco-open/test-telemetry-generator#92]
## Problem Statement

We already have a reasonable library of expressions for generating attribute values, metric values and many other things but we cannot possibly address all use cases that anyone could have. 

## Proposed Solution

We need a way for users to be able to pass in their implementation of `ELProcessor` in which they have added their custom expression implementations like we do here - https://github.com/cisco-open/test-telemetry-generator/blob/master/src/main/java/io/opentelemetry/contrib/generator/core/jel/JELProvider.java#L50. This would only be possible in the library mode and this implementation would benefit from being available for as many expression supported fields as we have.

**Comment by svrnm** [comment]
Although I have not used the library mode yet, I think this is a nice idea, it also makes it easier for people to extend test-telemetry-generator!
